import type { AnimationState } from "@/src/animations/types";

export function getRawSnippet(state: AnimationState): string {
  const speed = Number(state.params.speed ?? 0.7);
  const wheelAccel = 0.24 * speed;
  const immediateScroll = 0.35 * speed;
  const maxVelocity = 26 * speed;

  return [
    `"use client";`,
    ``,
    `import { useId, useLayoutEffect, useMemo, useRef, useState } from "react";`,
    ``,
    `const ROWS = ["Scroll down", "Watch it move", "Stay in sync"];`,
    `const LOOP_COPIES = 4;`,
    ``,
    `const clamp = (min: number, max: number, value: number) =>`,
    `  Math.min(max, Math.max(min, value));`,
    ``,
    `export function ScrollVelocityDemo() {`,
    `  const speed = ${speed.toFixed(2)};`,
    `  const WHEEL_ACCEL = ${wheelAccel.toFixed(3)};`,
    `  const FRICTION = 0.935;`,
    `  const MAX_VELOCITY = ${maxVelocity.toFixed(2)};`,
    `  const IMMEDIATE_SCROLL = ${immediateScroll.toFixed(3)};`,
    `  const STOP_THRESHOLD = 0.04;`,
    `  const MAX_VERTICAL_BLUR = 38;`,
    `  const BLUR_LERP = 0.22;`,
    ``,
    `  const filterId = useId().replace(/:/g, "");`,
    `  const viewportRef = useRef<HTMLDivElement>(null);`,
    `  const stripRef = useRef<HTMLDivElement>(null);`,
    `  const progressRef = useRef<HTMLDivElement>(null);`,
    `  const blurNodeRef = useRef<SVGFEGaussianBlurElement>(null);`,
    `  const rowRefs = useRef<(HTMLDivElement | null)[]>([]);`,
    `  const [hintVisible, setHintVisible] = useState(true);`,
    ``,
    `  const items = useMemo(`,
    `    () =>`,
    `      Array.from({ length: LOOP_COPIES }, (_, copy) =>`,
    `        ROWS.map((label) => ({ id: \`\${copy}-\${label}\`, label })),`,
    `      ).flat(),`,
    `    [],`,
    `  );`,
    ``,
    `  useLayoutEffect(() => {`,
    `    const viewport = viewportRef.current;`,
    `    const strip = stripRef.current;`,
    `    const progress = progressRef.current;`,
    `    const blurNode = blurNodeRef.current;`,
    `    const rows = rowRefs.current.filter(Boolean) as HTMLDivElement[];`,
    `    if (!viewport || !strip || !progress || !blurNode || !rows.length) return;`,
    ``,
    `    const prefersReduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches;`,
    `    let loopHeight = 0;`,
    `    let rowHeight = 0;`,
    `    let rowStep = 0;`,
    `    let stripPaddingTop = 0;`,
    `    let displayBlurY = 0;`,
    ``,
    `    const measure = () => {`,
    `      const firstRow = rows[0];`,
    `      if (!firstRow) return;`,
    `      rowHeight = firstRow.offsetHeight;`,
    `      rowStep = rowHeight + 14;`,
    `      stripPaddingTop = Math.max(0, viewport.clientHeight * 0.5 - rowHeight * 0.5);`,
    `      loopHeight = rowStep * ROWS.length;`,
    `      strip.style.paddingTop = \`\${stripPaddingTop}px\`;`,
    `      strip.style.height = \`\${loopHeight * LOOP_COPIES + stripPaddingTop + 16}px\`;`,
    `    };`,
    ``,
    `    measure();`,
    ``,
    `    const motion = { offset: loopHeight, velocity: 0 };`,
    ``,
    `    const applyTransform = (stretch = 1) => {`,
    `      if (loopHeight <= 0) return;`,
    `      while (motion.offset >= loopHeight) motion.offset -= loopHeight;`,
    `      while (motion.offset < 0) motion.offset += loopHeight;`,
    `      strip.style.transform = \`translate3d(0, \${-motion.offset}px, 0) scaleY(\${stretch.toFixed(4)})\`;`,
    `    };`,
    ``,
    `    const updateVelocityMeter = () => {`,
    `      const meterSpeed = clamp(0, 1, Math.abs(motion.velocity) / MAX_VELOCITY);`,
    `      progress.style.transform = \`scaleX(\${meterSpeed})\`;`,
    `    };`,
    ``,
    `    const updateMotionBlur = () => {`,
    `      const targetBlurY = clamp(0, MAX_VERTICAL_BLUR, Math.abs(motion.velocity) * 1.55);`,
    `      displayBlurY += (targetBlurY - displayBlurY) * BLUR_LERP;`,
    ``,
    `      if (displayBlurY > 0.2) {`,
    `        const blurX = displayBlurY * 0.06;`,
    `        blurNode.setAttribute("stdDeviation", \`\${blurX.toFixed(2)} \${displayBlurY.toFixed(2)}\`);`,
    `        strip.style.filter = \`url(#\${filterId})\`;`,
    `        const stretch = 1 + displayBlurY * 0.028;`,
    `        applyTransform(stretch);`,
    `      } else {`,
    `        displayBlurY = 0;`,
    `        blurNode.setAttribute("stdDeviation", "0 0");`,
    `        strip.style.filter = "none";`,
    `        applyTransform(1);`,
    `      }`,
    `    };`,
    ``,
    `    const updateRowFocus = () => {`,
    `      const viewportHeight = viewport.clientHeight;`,
    `      const center = viewportHeight * 0.5;`,
    `      rows.forEach((row, index) => {`,
    `        const rowCenter = stripPaddingTop + index * rowStep + rowHeight * 0.5 - motion.offset;`,
    `        const distance = Math.abs(rowCenter - center);`,
    `        const focus = clamp(0.22, 1, 1 - distance / (viewportHeight * 0.55));`,
    `        row.style.opacity = String(focus);`,
    `      });`,
    `    };`,
    ``,
    `    const render = () => {`,
    `      updateMotionBlur();`,
    `      updateVelocityMeter();`,
    `      updateRowFocus();`,
    `    };`,
    ``,
    `    if (prefersReduced) {`,
    `      progress.style.transform = "scaleX(0)";`,
    `      strip.style.filter = "none";`,
    `      applyTransform(1);`,
    `      rows.forEach((row) => { row.style.opacity = "1"; });`,
    `      return;`,
    `    }`,
    ``,
    `    render();`,
    `    let rafId = 0;`,
    `    const tick = () => {`,
    `      const moving = Math.abs(motion.velocity) > STOP_THRESHOLD;`,
    `      if (moving) {`,
    `        motion.offset += motion.velocity;`,
    `        motion.velocity *= FRICTION;`,
    `        render();`,
    `      } else {`,
    `        if (motion.velocity !== 0) motion.velocity = 0;`,
    `        if (displayBlurY > 0.2) {`,
    `          displayBlurY += (0 - displayBlurY) * BLUR_LERP;`,
    `          updateMotionBlur();`,
    `          updateRowFocus();`,
    `        }`,
    `        updateVelocityMeter();`,
    `      }`,
    `      rafId = requestAnimationFrame(tick);`,
    `    };`,
    `    rafId = requestAnimationFrame(tick);`,
    ``,
    `    const onWheel = (event: WheelEvent) => {`,
    `      event.preventDefault();`,
    `      event.stopPropagation();`,
    `      setHintVisible(false);`,
    `      motion.velocity += event.deltaY * WHEEL_ACCEL;`,
    `      motion.velocity = clamp(-MAX_VELOCITY, MAX_VELOCITY, motion.velocity);`,
    `      motion.offset += event.deltaY * IMMEDIATE_SCROLL;`,
    `      render();`,
    `    };`,
    ``,
    `    const onResize = () => { measure(); render(); };`,
    ``,
    `    viewport.addEventListener("wheel", onWheel, { passive: false });`,
    `    const resizeObserver = typeof ResizeObserver !== "undefined" ? new ResizeObserver(onResize) : null;`,
    `    resizeObserver?.observe(viewport);`,
    ``,
    `    return () => {`,
    `      cancelAnimationFrame(rafId);`,
    `      viewport.removeEventListener("wheel", onWheel);`,
    `      resizeObserver?.disconnect();`,
    `    };`,
    `  }, [filterId, items.length, speed, WHEEL_ACCEL, MAX_VELOCITY, IMMEDIATE_SCROLL]);`,
    ``,
    `  return (`,
    `    <div style={{ width: "100%", height: "100%" }}>`,
    `      {/* include the module CSS from the demo for styling */}`,
    `      <svg aria-hidden focusable="false" style={{ position: "absolute", width: 0, height: 0, overflow: "hidden" }}>`,
    `        <defs>`,
    `          <filter id={filterId} x="-120%" y="-120%" width="340%" height="340%" colorInterpolationFilters="sRGB">`,
    `            <feGaussianBlur ref={blurNodeRef} in="SourceGraphic" stdDeviation="0 0" />`,
    `          </filter>`,
    `        </defs>`,
    `      </svg>`,
    ``,
    `      <div>`,
    `        <span>Velocity</span>`,
    `        <div aria-hidden>`,
    `          <div ref={progressRef} />`,
    `        </div>`,
    `      </div>`,
    ``,
    `      <div`,
    `        ref={viewportRef}`,
    `        tabIndex={0}`,
    `        role="region"`,
    `        aria-label="Scroll Velocity interactive preview — scroll inside to explore momentum"`,
    `      >`,
    `        <div ref={stripRef}>`,
    `          {items.map((item, index) => (`,
    `            <div`,
    `              key={item.id}`,
    `              ref={(node) => { rowRefs.current[index] = node; }}`,
    `            >`,
    `              <span aria-hidden />`,
    `              <span>{item.label}</span>`,
    `            </div>`,
    `          ))}`,
    `        </div>`,
    `      </div>`,
    ``,
    `      <p aria-hidden style={{ opacity: hintVisible ? 1 : 0 }}>Scroll inside</p>`,
    `    </div>`,
    `  );`,
    `}`,
    ``,
  ].join("\n");
}

export function getHighlightedSnippet(
  state: AnimationState,
  lastChangedKey: string | null,
): string {
  const speed = Number(state.params.speed ?? 0.7);
  const wheelAccel = 0.24 * speed;
  const immediateScroll = 0.35 * speed;
  const maxVelocity = 26 * speed;

  const kw = (t: string) => `<span style="color:#c792ea">${t}</span>`; // keywords
  const fn = (t: string) => `<span style="color:#82aaff">${t}</span>`; // functions / components
  const str = (t: string) => `<span style="color:#c3e88d">${t}</span>`; // strings
  const num = (t: string) => `<span style="color:#f78c6c">${t}</span>`; // numbers
  const prop = (t: string) => `<span style="color:#89ddff">${t}</span>`; // object keys / props
  const pn = (t: string) => `<span style="color:rgba(255,255,255,0.5)">${t}</span>`; // punctuation

  function maybeHighlight(key: string, html: string) {
    return lastChangedKey === key
      ? `<span style="color:#feb800">${html}</span>`
      : html;
  }

  function line(content: string) {
    return `<span style="display:block">${content}</span>`;
  }

  const speedLit = maybeHighlight("speed", num(speed.toFixed(2)));
  const wheelAccelLit = maybeHighlight(
    "speed",
    num(wheelAccel.toFixed(3)),
  );
  const maxVelocityLit = maybeHighlight(
    "speed",
    num(maxVelocity.toFixed(2)),
  );
  const immediateScrollLit = maybeHighlight(
    "speed",
    num(immediateScroll.toFixed(3)),
  );

  return [
    line(`${kw("export")} ${kw("function")} ${fn("ScrollVelocityDemo")}${pn("()")} ${pn("{")}`),
    line(`  ${kw("const")} speed ${pn("=")} ${speedLit}${pn(";")}`),
    line(`  ${kw("const")} WHEEL_ACCEL ${pn("=")} ${wheelAccelLit}${pn(";")}`),
    line(`  ${kw("const")} MAX_VELOCITY ${pn("=")} ${maxVelocityLit}${pn(";")}`),
    line(`  ${kw("const")} IMMEDIATE_SCROLL ${pn("=")} ${immediateScrollLit}${pn(";")}`),
    line(`  ${pn("// ... rest of component + wheel handler + JSX ...")}`),
    line(`${pn("}")}`),
    line(` `),
    line(
      `${pn("// Full source is copy-pastable via the button above (raw snippet).")}`,
    ),
    line(
      `${pn("// Styles live in")} ${str("'./demo.css'")} ${pn("in this repo.")}`,
    ),
  ].join("\n");
}
