import type { AnimationState } from "@/src/animations/types";

export function getRawSnippet(state: AnimationState): string {
  const chaos = Number(state.params.chaos ?? 3.1);
  const repulsionStrength = Number(state.params.repulsionStrength ?? 9);
  const radius = Number(state.params.radius ?? 200);

  return [
    `"use client";`,
    ``,
    `import { useLayoutEffect, useRef } from "react";`,
    ``,
    `const BASE = {`,
    `  text: "Motion",`,
    `  ambientBrownian: 3.0,`,
    `  elasticity: 0.03,`,
    `  damping: 0.81,`,
    `  densityGap: 5,`,
    `  particleSize: 2.3,`,
    `};`,
    ``,
    `class Particle {`,
    `  x: number; y: number; homeX: number; homeY: number; vx = 0; vy = 0;`,
    `  constructor(x: number, y: number) { this.x = x; this.y = y; this.homeX = x; this.homeY = y; }`,
    `}`,
    ``,
    `export function ParticleTextDemo() {`,
    `  const chaos = ${chaos.toFixed(2)};`,
    `  const repulsionStrength = ${repulsionStrength.toFixed(2)};`,
    `  const radius = ${radius.toFixed(0)};`,
    ``,
    `  const rootRef = useRef<HTMLDivElement>(null);`,
    `  const canvasRef = useRef<HTMLCanvasElement>(null);`,
    `  const configRef = useRef({ chaos, repulsionStrength, radius });`,
    ``,
    `  useLayoutEffect(() => {`,
    `    configRef.current = { chaos, repulsionStrength, radius };`,
    `  }, [chaos, repulsionStrength, radius]);`,
    ``,
    `  useLayoutEffect(() => {`,
    `    const root = rootRef.current;`,
    `    const canvas = canvasRef.current;`,
    `    if (!root || !canvas) return;`,
    ``,
    `    const prefersReduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches;`,
    `    const ctx = canvas.getContext("2d", { willReadFrequently: true });`,
    `    if (!ctx) return;`,
    ``,
    `    const mouse = { x: null as number | null, y: null as number | null };`,
    `    let particles: Particle[] = [];`,
    `    let animationId: number | null = null;`,
    `    let width = 0;`,
    `    let height = 0;`,
    ``,
    `    const setPointer = (clientX: number, clientY: number) => {`,
    `      const rect = canvas.getBoundingClientRect();`,
    `      const scaleX = width / rect.width;`,
    `      const scaleY = height / rect.height;`,
    `      mouse.x = (clientX - rect.left) * scaleX;`,
    `      mouse.y = (clientY - rect.top) * scaleY;`,
    `    };`,
    ``,
    `    const clearPointer = () => { mouse.x = null; mouse.y = null; };`,
    ``,
    `    const initParticles = () => {`,
    `      if (width <= 0 || height <= 0) return;`,
    `      particles = [];`,
    `      const baseSize = Math.min(width * 0.38, height * 0.58, 120);`,
    `      ctx.fillStyle = "#ffffff";`,
    `      ctx.font = \`bold \${baseSize}px Arial, sans-serif\`;`,
    `      ctx.textAlign = "center";`,
    `      ctx.textBaseline = "middle";`,
    `      ctx.clearRect(0, 0, width, height);`,
    `      ctx.fillText(BASE.text, width / 2, height / 2);`,
    `      const textPixels = ctx.getImageData(0, 0, width, height);`,
    `      ctx.clearRect(0, 0, width, height);`,
    ``,
    `      const { data } = textPixels;`,
    `      const w = textPixels.width;`,
    `      const h = textPixels.height;`,
    `      const step = BASE.densityGap;`,
    `      for (let y = 0; y < h; y += step) {`,
    `        for (let x = 0; x < w; x += step) {`,
    `          const alpha = data[(y * w + x) * 4 + 3];`,
    `          if (alpha > 120) particles.push(new Particle(x, y));`,
    `        }`,
    `      }`,
    `    };`,
    ``,
    `    const resize = () => {`,
    `      const nextWidth = Math.max(1, Math.floor(root.clientWidth));`,
    `      const nextHeight = Math.max(1, Math.floor(root.clientHeight));`,
    `      if (nextWidth === width && nextHeight === height) return;`,
    `      width = nextWidth;`,
    `      height = nextHeight;`,
    `      canvas.width = width;`,
    `      canvas.height = height;`,
    `      initParticles();`,
    `    };`,
    ``,
    `    const updateParticle = (p: Particle) => {`,
    `      const cfg = configRef.current;`,
    `      let forceX = (p.homeX - p.x) * BASE.elasticity;`,
    `      let forceY = (p.homeY - p.y) * BASE.elasticity;`,
    ``,
    `      if (mouse.x !== null && mouse.y !== null) {`,
    `        const mdx = mouse.x - p.x;`,
    `        const mdy = mouse.y - p.y;`,
    `        const distance = Math.sqrt(mdx * mdx + mdy * mdy);`,
    `        if (distance < cfg.radius) {`,
    `          const ratio = (cfg.radius - distance) / cfg.radius;`,
    `          const baseAngle = Math.atan2(mdy, mdx);`,
    `          const angleScatter = (Math.random() - 0.5) * cfg.chaos * 0.8;`,
    `          const pushAngle = baseAngle + angleScatter;`,
    `          const pushStrength = cfg.repulsionStrength * (0.3 + cfg.chaos * 0.7) * 0.05 * ratio;`,
    `          forceX -= Math.cos(pushAngle) * pushStrength;`,
    `          forceY -= Math.sin(pushAngle) * pushStrength;`,
    `        }`,
    `      }`,
    ``,
    `      forceX += (Math.random() - 0.5) * BASE.ambientBrownian * 0.08;`,
    `      forceY += (Math.random() - 0.5) * BASE.ambientBrownian * 0.08;`,
    `      p.vx += forceX;`,
    `      p.vy += forceY;`,
    `      p.vx *= BASE.damping;`,
    `      p.vy *= BASE.damping;`,
    `      p.x += p.vx;`,
    `      p.y += p.vy;`,
    `    };`,
    ``,
    `    const drawParticle = (p: Particle) => {`,
    `      ctx.fillStyle = "#ffffff";`,
    `      ctx.beginPath();`,
    `      ctx.arc(p.x, p.y, BASE.particleSize, 0, Math.PI * 2);`,
    `      ctx.fill();`,
    `    };`,
    ``,
    `    const animate = () => {`,
    `      ctx.clearRect(0, 0, width, height);`,
    `      for (let i = 0; i < particles.length; i += 1) {`,
    `        updateParticle(particles[i]);`,
    `        drawParticle(particles[i]);`,
    `      }`,
    `      animationId = requestAnimationFrame(animate);`,
    `    };`,
    ``,
    `    resize();`,
    `    if (prefersReduced) {`,
    `      ctx.clearRect(0, 0, width, height);`,
    `      particles.forEach((p) => drawParticle(p));`,
    `    } else {`,
    `      animate();`,
    `    }`,
    ``,
    `    const resizeObserver = new ResizeObserver(resize);`,
    `    resizeObserver.observe(root);`,
    `    const onPointerMove = (event: PointerEvent) => setPointer(event.clientX, event.clientY);`,
    `    canvas.addEventListener("pointermove", onPointerMove);`,
    `    canvas.addEventListener("pointerleave", clearPointer);`,
    ``,
    `    return () => {`,
    `      if (animationId !== null) cancelAnimationFrame(animationId);`,
    `      resizeObserver.disconnect();`,
    `      canvas.removeEventListener("pointermove", onPointerMove);`,
    `      canvas.removeEventListener("pointerleave", clearPointer);`,
    `    };`,
    `  }, [chaos, repulsionStrength, radius]);`,
    ``,
    `  return (`,
    `    <div ref={rootRef} style={{ position: "relative", width: "100%", height: "100%", overflow: "hidden" }}>`,
    `      <canvas ref={canvasRef} style={{ position: "absolute", inset: 0, width: "100%", height: "100%" }} aria-hidden />`,
    `    </div>`,
    `  );`,
    `}`,
    ``,
  ].join("\n");
}

export function getHighlightedSnippet(
  state: AnimationState,
  lastChangedKey: string | null,
): string {
  const chaos = Number(state.params.chaos ?? 3.1);
  const repulsionStrength = Number(state.params.repulsionStrength ?? 9);
  const radius = Number(state.params.radius ?? 200);

  const kw = (t: string) => `<span style="color:#d0d2cc">${t}</span>`;
  const fn = (t: string) => `<span style="color:#ffffff">${t}</span>`;
  const num = (t: string) => `<span style="color:#e2e2e2">${t}</span>`;
  const pn = (t: string) => `<span style="color:rgba(255,255,255,0.45)">${t}</span>`;

  const h = (key: string, html: string) =>
    lastChangedKey === key ? `<span style="color:#feb800">${html}</span>` : html;

  function line(content: string) {
    return `<span style="display:block">${content}</span>`;
  }

  return [
    line(`${kw("export")} ${kw("function")} ${fn("ParticleTextDemo")}${pn("()")} ${pn("{")}`),
    line(`  ${kw("const")} chaos ${pn("=")} ${h("chaos", num(chaos.toFixed(2)))}${pn(";")}`),
    line(`  ${kw("const")} repulsionStrength ${pn("=")} ${h("repulsionStrength", num(repulsionStrength.toFixed(2)))}${pn(";")}`),
    line(`  ${kw("const")} radius ${pn("=")} ${h("radius", num(radius.toFixed(0)))}${pn(";")} ${pn("// px")}`),
    line(`  ${pn("// ... canvas particle system ...")}`),
    line(`${pn("}")}`),
  ].join("\n");
}
