import type { ControlSchema } from "@/src/animations/types";

export const controlSchema: ControlSchema = [
  {
    key: "minDistance",
    label: "Spawn distance",
    min: 4,
    max: 40,
    step: 1,
    decimals: 0,
    unit: "px",
    defaultValue: 14,
  },
  {
    key: "maxParticles",
    label: "Max particles",
    min: 8,
    max: 96,
    step: 1,
    decimals: 0,
    unit: "",
    defaultValue: 48,
  },
  {
    key: "particleSizeMin",
    label: "Size min",
    min: 16,
    max: 64,
    step: 1,
    decimals: 0,
    unit: "px",
    defaultValue: 36,
  },
  {
    key: "particleSizeMax",
    label: "Size max",
    min: 24,
    max: 80,
    step: 1,
    decimals: 0,
    unit: "px",
    defaultValue: 52,
  },
  {
    key: "durationMin",
    label: "Fade min",
    min: 0.3,
    max: 1.5,
    step: 0.05,
    decimals: 2,
    unit: "s",
    defaultValue: 0.65,
  },
  {
    key: "durationMax",
    label: "Fade max",
    min: 0.4,
    max: 2,
    step: 0.05,
    decimals: 2,
    unit: "s",
    defaultValue: 1.05,
  },
];
