import type { ControlSchema } from "@/src/animations/types";

export const controlSchema: ControlSchema = [
  {
    key: "waveDuration",
    label: "Wave duration",
    min: 0.35,
    max: 2.2,
    step: 0.05,
    decimals: 2,
    unit: "s",
    defaultValue: 1.05,
  },
  {
    key: "stagger",
    label: "Stagger",
    min: 0.02,
    max: 0.18,
    step: 0.005,
    decimals: 3,
    unit: "s",
    defaultValue: 0.095,
  },
  {
    key: "scrub",
    label: "Scrub smoothing",
    min: 0.4,
    max: 3.5,
    step: 0.05,
    decimals: 2,
    unit: "",
    defaultValue: 1.85,
  },
  {
    key: "travel",
    label: "Vertical travel",
    min: 30,
    max: 70,
    step: 1,
    decimals: 0,
    unit: "vh",
    defaultValue: 52,
  },
  {
    key: "segmentHeight",
    label: "Scroll depth",
    min: 1.0,
    max: 3.0,
    step: 0.05,
    decimals: 2,
    unit: "× viewport",
    defaultValue: 1.75,
  },
];
